services:
  web:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - "env.${RAILS_ENV:-development}"
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_USER: sms
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
